### ISSUE TITLE
mscharts multiplies the y-axis by 100 and adds an extra "%" - ESM

### ISSUE THREAD

**Issue by ethansm1209** [y2analytics/y2artisan#2]
When I print out an mschart (bar chart, line chart, etc.), the y-axis is multiplied by 100 and it adds an extra "%" to the axis tick labels. The scale for the values themselves seems to be correct (for example, a bar chart with a bar that goes up to 70% will appear to be going up to where 70% _should be_ on the bar chart, but the y-axis will be saying that it's at "7000%%"). Wallace encountered this issue immediately after updating. 

```
library(tidyverse)
library(y2clerk)
library(y2artisan)

frequencies <- mtcars %>% 
  freq(mpg)

color_settings <- list(
  "blue"
)

text_settings <- list(
  fp_text(color = "blue")
)

chart <- ms_single_y2(
  axis
)

print(chart, preview = TRUE)
```

I should expect to see a bar chart with the y-axis going from 0% to 7%. Instead the range is 0%% to 700%%. 

**System details**
y2artisan 0.6.4
RStudio Version 2022.12.0+353 (2022.12.0+353)

**Screenshots**
<img width="845" alt="Screen Shot 2023-03-16 at 11 51 23 AM" src="https://user-images.githubusercontent.com/100870923/225708988-cef1ec1b-7b06-4ecc-b713-416811d4be8c.png">

**Priority**
 - Medium

**Comment by nick-moffitt** [comment]
Fixed in version 0.6.5
