### ISSUE TITLE
Read in powerpoint template function

### ISSUE THREAD

**Issue by tatiana-gilchrist** [y2analytics/y2artisan#3]
**Describe the solution you'd like**
I would like a function I can run in R that automatically reads the standard ms powerpoint into R. Something like read_doc and it just saves a powerpoint report called doc in the environment. 

**Describe alternatives you've considered**
I mean I just read it in by hand and it's not the vibe. 

**Priority**
- Low

**Comment by nick-moffitt** [comment]
Tatiana and I discussed. We'll stick with read_pptx() for now.
